backend:
  name: git-gateway
  branch: main # Branch to update (main, master, etc.)

media_folder: "static/img" # Media files will be stored in this folder
public_folder: "/img"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}